export const SERVICE_URL = {
	home: '/',
	register: '/register',
	inventory: '/inventory',
	inventoryHistory: '/inventory/history',
	inventoryCigarette: '/inventory/cigarette',
	inventoryCard: '/inventory/gift-card',
	inventoryBag: '/inventory/garbage-bag',
	mypage: '/mypage',
	profileSetting: '/mypage/setting',
	editWorkTime: '/mypage/setting/work-time',
	editPhoneNumber: '/mypage/setting/phone',
	myStore: '/mypage/store',
	calendar: '/calendar',
	calendarModify: '/calendar/work-modify',
	calendarSalary: '/calendar/salary',
	calendarSalaryDetail: '/calendar/salary-detail',
};
