export const SERVICE_URL = {
	home: '/',
	register: '/register',
	checklist: '/checklist',
	inventory: '/inventory',
	inventoryHistory: '/inventory/history',
	inventoryCigarette: '/inventory/cigarette',
	inventoryCard: '/inventory/gift-card',
	inventoryBag: '/inventory/garbage-bag',
	mypage: '/mypage',
	profileSetting: '/mypage/setting',
	editWorkTime: '/mypage/setting/work-time',
	editPhoneNumber: '/mypage/setting/phone',
	editWage: '/mypage/setting/wage',
	myStore: '/mypage/store',
	calendar: '/calendar',
	calendarRecord: '/calendar/work-record',
	calendarSalary: '/calendar/salary',
	calendarSalaryDetail: '/calendar/salary-detail',
	board: '/board',
	boardWrite: '/board/write',
	boardView: '/board/view',
};
